# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-27 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magic_cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='loyalty',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
