# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-06 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import magic_cards.models


class Migration(migrations.Migration):

    dependencies = [
        ('magic_cards', '0002_card_loyalty'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignPrinting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('language', models.CharField(choices=[('de', 'German'), ('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('it', 'Italian'), ('ja', 'Japanese'), ('ko', 'Korean'), ('pt', 'Portuguese'), ('ru', 'Russian'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese')], max_length=7)),
                ('multiverse_id', models.PositiveIntegerField(blank=True, null=True)),
                ('base_printing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foreign_printings', to='magic_cards.Printing')),
            ],
            bases=(magic_cards.models.NameMixin, models.Model),
        ),
    ]
