# Generated by Django 2.2 on 2019-05-10 02:30

from django.db import migrations, models


def wipe_db(apps, schema_editor):
    for model in ("Card", "Printing", "Set", "CardSupertype", "CardSubtype",
                  "CardType", "Artist"):
        apps.get_model("magic_cards", model).objects.all().delete()


def noop(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('magic_cards', '0002_card_loyalty'),
    ]

    operations = [
        migrations.RunPython(
            wipe_db,
            noop,
        ),
        migrations.AlterField(
            model_name='card',
            name='loyalty',
            field=models.CharField(max_length=8, null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='printing',
            name='number',
            field=models.CharField(max_length=64, blank=True),
        ),
        migrations.AlterField(
            model_name='printing',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.deletion.CASCADE, related_name='printings', to='magic_cards.Artist'),
        ),
        migrations.RunPython(
            noop,
            wipe_db,
        ),
    ]
